### ISSUE TITLE
UnicodeDecordeError

### ISSUE THREAD

**Issue by PeterPablo** [markbirbeck/sublime-text-shell-command#38]
Thank you for your nice plugin! When executing `make` the command that is actually executed is `latexmk`. The plugin seems to have an issue parsing the output at some point.

Here is the last line of output:
`[19 <./ext_fig/doc-figure5.pdf>]
Overfull \hbox (24.43933pt too wide) in paragraph at lines 235--236`

Here is the log from the console:
```
Exception in thread Thread-1305:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "OsShell in /home/user/.config/sublime-text-3/Installed Packages/Shell Command.sublime-package", line 105, in _process
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 38: invalid continuation byte
```

I hope this is enough for you to solve the issue. (It is reproducible and as such I can test it.)

If I execute a similar command that results in shorter output, everything works as expected.
I am on ST3 with Ubuntu 12.04 and the package installed over the package manager.

**Comment by PeterPablo** [comment]
I solved the issue of an overfull line in the latex code and afterwards the execution of the process works just fine. As such it really must be some kind of (control) character being present in the output of latexmk, when that kind of `Overfull \hbox` warning is printed.

**Comment by PeterPablo** [comment]
Please have a look at [how](https://github.com/SublimeText/LaTeXTools/blob/master/makePDF.py#L138) `LaTexTools` handles the output.
